"""alteracao de preco

Revision ID: 0fecf9eb16c5
Revises: 203657e6c9b0
Create Date: 2024-11-27 15:34:12.785221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fecf9eb16c5'
down_revision: Union[str, None] = '203657e6c9b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('preco_promocional', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'preco_promocional')
    # ### end Alembic commands ###
