"""Corrigir codigo

Revision ID: 48c236ac4b36
Revises: f3354ad1d395
Create Date: 2024-12-13 17:20:02.957289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c236ac4b36'
down_revision: Union[str, None] = 'f3354ad1d395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('info_usuario', 'contacto')
    op.add_column('usuarios', sa.Column('contacto', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'contacto')
    op.add_column('info_usuario', sa.Column('contacto', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
