"""alteracao de infousuario

Revision ID: 545e901a1fac
Revises: 
Create Date: 2024-11-24 10:50:16.075399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545e901a1fac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_likes')
    op.drop_index('ix_endereco_envio_id', table_name='endereco_envio')
    op.drop_table('endereco_envio')
    op.drop_index('ix_anuncio_id', table_name='anuncio')
    op.drop_table('anuncio')
    op.drop_index('ix_produto_id', table_name='produto')
    op.drop_index('ix_produto_slug', table_name='produto')
    op.drop_table('produto')
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.drop_index('ix_usuarios_id', table_name='usuarios')
    op.drop_index('ix_usuarios_username', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index('ix_info_usuario_id', table_name='info_usuario')
    op.drop_table('info_usuario')
    op.drop_index('ix_status_id', table_name='status')
    op.drop_table('status')
    op.drop_index('ix_denunciaProduto_id', table_name='denunciaProduto')
    op.drop_table('denunciaProduto')
    op.drop_index('ix_seguidores_id', table_name='seguidores')
    op.drop_table('seguidores')
    op.drop_index('ix_pedido_id', table_name='pedido')
    op.drop_table('pedido')
    op.drop_index('ix_comentario_comentarioID', table_name='comentario')
    op.drop_table('comentario')
    op.drop_index('ix_admin_id', table_name='admin')
    op.drop_table('admin')
    op.drop_index('ix_pesquisas_id', table_name='pesquisas')
    op.drop_index('ix_pesquisas_termo_pesquisa', table_name='pesquisas')
    op.drop_table('pesquisas')
    op.drop_index('ix_transacoes_id', table_name='transacoes')
    op.drop_table('transacoes')
    op.drop_index('ix_notificacoes_id', table_name='notificacoes')
    op.drop_table('notificacoes')
    op.drop_index('ix_wallet_id', table_name='wallet')
    op.drop_table('wallet')
    op.drop_index('ix_messages_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_publicacoes_id', table_name='publicacoes')
    op.drop_table('publicacoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicacoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('conteudo', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_publicacoes_id', 'publicacoes', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('message_type', sa.VARCHAR(length=5), nullable=False),
    sa.Column('file_url', sa.VARCHAR(), nullable=True),
    sa.Column('file_name', sa.VARCHAR(), nullable=True),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_id', 'messages', ['id'], unique=False)
    op.create_table('wallet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('saldo_principal', sa.DECIMAL(), nullable=True),
    sa.Column('saldo_congelado', sa.DECIMAL(), nullable=True),
    sa.Column('bonus', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index('ix_wallet_id', 'wallet', ['id'], unique=False)
    op.create_table('notificacoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('mensagem', sa.VARCHAR(length=255), nullable=False),
    sa.Column('data', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notificacoes_id', 'notificacoes', ['id'], unique=False)
    op.create_table('transacoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('msisdn', sa.VARCHAR(), nullable=False),
    sa.Column('valor', sa.DECIMAL(), nullable=False),
    sa.Column('referencia', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('data_hora', sa.DATETIME(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transacoes_id', 'transacoes', ['id'], unique=False)
    op.create_table('pesquisas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('termo_pesquisa', sa.VARCHAR(), nullable=True),
    sa.Column('categoria_pesquisa', sa.VARCHAR(), nullable=True),
    sa.Column('data_pesquisa', sa.DATETIME(), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pesquisas_termo_pesquisa', 'pesquisas', ['termo_pesquisa'], unique=False)
    op.create_index('ix_pesquisas_id', 'pesquisas', ['id'], unique=False)
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=255), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_admin_id', 'admin', ['id'], unique=False)
    op.create_table('comentario',
    sa.Column('comentarioID', sa.INTEGER(), nullable=False),
    sa.Column('produtoID', sa.INTEGER(), nullable=True),
    sa.Column('CustomerID', sa.INTEGER(), nullable=True),
    sa.Column('comentario', sa.TEXT(), nullable=True),
    sa.Column('data_comentario', sa.DATETIME(), nullable=True),
    sa.Column('avaliacao', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['produtoID'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('comentarioID')
    )
    op.create_index('ix_comentario_comentarioID', 'comentario', ['comentarioID'], unique=False)
    op.create_table('pedido',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.Column('produto_id', sa.INTEGER(), nullable=True),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('preco_unitario', sa.DECIMAL(), nullable=True),
    sa.Column('preco_total', sa.DECIMAL(), nullable=True),
    sa.Column('data_pedido', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=350), nullable=True),
    sa.Column('aceito_pelo_vendedor', sa.BOOLEAN(), nullable=True),
    sa.Column('recebido_pelo_cliente', sa.BOOLEAN(), nullable=True),
    sa.Column('data_aceite', sa.DATETIME(), nullable=True),
    sa.Column('data_envio', sa.DATETIME(), nullable=True),
    sa.Column('data_entrega', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pedido_id', 'pedido', ['id'], unique=False)
    op.create_table('seguidores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.Column('seguidor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['seguidor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seguidores_id', 'seguidores', ['id'], unique=False)
    op.create_table('denunciaProduto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('produtoID', sa.INTEGER(), nullable=True),
    sa.Column('CustomerID', sa.INTEGER(), nullable=True),
    sa.Column('motivo', sa.VARCHAR(length=350), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('data_denuncia', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=350), nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['produtoID'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_denunciaProduto_id', 'denunciaProduto', ['id'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('conteudo', sa.TEXT(), nullable=True),
    sa.Column('imagem_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('expira_em', sa.DATETIME(), nullable=False),
    sa.Column('custo_total', sa.DECIMAL(), nullable=False),
    sa.Column('visualizacoes', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_status_id', 'status', ['id'], unique=False)
    op.create_table('info_usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('perfil', sa.VARCHAR(length=350), nullable=True),
    sa.Column('provincia', sa.VARCHAR(length=350), nullable=True),
    sa.Column('foto_bi', sa.VARCHAR(length=350), nullable=True),
    sa.Column('distrito', sa.VARCHAR(length=350), nullable=True),
    sa.Column('data_nascimento', sa.VARCHAR(length=350), nullable=True),
    sa.Column('localizacao', sa.VARCHAR(length=350), nullable=True),
    sa.Column('avenida', sa.VARCHAR(length=255), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=350), nullable=True),
    sa.Column('sexo', sa.VARCHAR(length=20), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=10), nullable=True),
    sa.Column('nacionalidade', sa.VARCHAR(length=255), nullable=True),
    sa.Column('revisao', sa.VARCHAR(length=255), nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=255), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_info_usuario_id', 'info_usuario', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nome', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('senha', sa.VARCHAR(length=255), nullable=True),
    sa.Column('google_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=255), nullable=True),
    sa.Column('foto_perfil', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('conta_pro', sa.BOOLEAN(), nullable=True),
    sa.Column('limite_diario_publicacoes', sa.INTEGER(), nullable=True),
    sa.Column('data_cadastro', sa.DATETIME(), nullable=True),
    sa.Column('data_ativacao_pro', sa.DATETIME(), nullable=True),
    sa.Column('revisao', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index('ix_usuarios_username', 'usuarios', ['username'], unique=1)
    op.create_index('ix_usuarios_id', 'usuarios', ['id'], unique=False)
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=1)
    op.create_table('produto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=350), nullable=True),
    sa.Column('capa', sa.VARCHAR(length=350), nullable=True),
    sa.Column('fotos', sa.VARCHAR(length=350), nullable=True),
    sa.Column('preco', sa.DECIMAL(), nullable=True),
    sa.Column('quantidade_estoque', sa.INTEGER(), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=350), nullable=True),
    sa.Column('provincia', sa.VARCHAR(length=20), nullable=True),
    sa.Column('distrito', sa.VARCHAR(length=20), nullable=True),
    sa.Column('revisao', sa.VARCHAR(length=350), nullable=True),
    sa.Column('disponiblidade', sa.VARCHAR(length=350), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=350), nullable=True),
    sa.Column('detalhes', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=350), nullable=True),
    sa.Column('visualizacoes', sa.INTEGER(), nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.Column('CustomerID', sa.INTEGER(), nullable=True),
    sa.Column('likes', sa.INTEGER(), nullable=True),
    sa.Column('data_publicacao', sa.DATETIME(), nullable=True),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_produto_slug', 'produto', ['slug'], unique=1)
    op.create_index('ix_produto_id', 'produto', ['id'], unique=False)
    op.create_table('anuncio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=350), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('tipo_anuncio', sa.VARCHAR(length=350), nullable=True),
    sa.Column('produto_id', sa.INTEGER(), nullable=True),
    sa.Column('promovido_em', sa.DATETIME(), nullable=True),
    sa.Column('expira_em', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id')
    )
    op.create_index('ix_anuncio_id', 'anuncio', ['id'], unique=False)
    op.create_table('endereco_envio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('CustomerID', sa.INTEGER(), nullable=True),
    sa.Column('pedidoID', sa.INTEGER(), nullable=True),
    sa.Column('endereco_line1', sa.VARCHAR(length=350), nullable=True),
    sa.Column('endereco_line2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cidade', sa.VARCHAR(length=350), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=350), nullable=True),
    sa.Column('codigo_postal', sa.VARCHAR(length=350), nullable=True),
    sa.Column('pais', sa.VARCHAR(length=350), nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['pedidoID'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_endereco_envio_id', 'endereco_envio', ['id'], unique=False)
    op.create_table('produto_likes',
    sa.Column('produto_id', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('produto_id', 'usuario_id')
    )
    # ### end Alembic commands ###
