"""Corrigir chave estrangeira e relacionamentos

Revision ID: afaf50d405e4
Revises: fc2bfe4743e1
Create Date: 2024-12-10 10:44:40.614133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afaf50d405e4'
down_revision: Union[str, None] = 'fc2bfe4743e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
