"""Revisão final

Revision ID: b7e561eb4ccc
Revises: bdf21f7c2f7f
Create Date: 2024-12-10 10:06:26.608343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7e561eb4ccc'
down_revision: Union[str, None] = 'bdf21f7c2f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_acao', sa.String(), nullable=False),
    sa.Column('entidade', sa.String(), nullable=False),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produtoID', sa.Integer(), nullable=False),
    sa.Column('usuarioID', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=False),
    sa.Column('data_comentario', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produtoID'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['usuarioID'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_id'), 'comentarios', ['id'], unique=False)
    op.drop_index('ix_comentario_comentarioID', table_name='comentario')
    op.drop_table('comentario')
    op.add_column('usuarios', sa.Column('min_perfil', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'min_perfil')
    op.create_table('comentario',
    sa.Column('comentarioID', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('produtoID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CustomerID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_comentario', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['usuarios.id'], name='comentario_CustomerID_fkey'),
    sa.ForeignKeyConstraint(['produtoID'], ['produto.id'], name='comentario_produtoID_fkey'),
    sa.PrimaryKeyConstraint('comentarioID', name='comentario_pkey')
    )
    op.create_index('ix_comentario_comentarioID', 'comentario', ['comentarioID'], unique=False)
    op.drop_index(op.f('ix_comentarios_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
