"""Corrigir chave estrangeira e relacionamentos

Revision ID: d8c64df97603
Revises: afaf50d405e4
Create Date: 2024-12-10 12:07:00.011671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c64df97603'
down_revision: Union[str, None] = 'afaf50d405e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
