"""Corrigir chave estrangeira e relacionamentos

Revision ID: fc2bfe4743e1
Revises: b7e561eb4ccc
Create Date: 2024-12-10 10:30:27.939943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc2bfe4743e1'
down_revision: Union[str, None] = 'b7e561eb4ccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
